name: NewsAPI Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install -y jq

      - name: Get News
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          mkdir -p posts

          curl -L \
          "https://newsapi.org/v2/top-headlines?country=us&category=technology&pageSize=1&apiKey=$NEWS_API_KEY" \
          -o news.json

          jq -r '.articles[0].title' news.json > posts/title.txt
          jq -r '.articles[0].urlToImage' news.json > posts/image.txt
          jq -r '.articles[0].url' news.json > posts/url.txt

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email actions@github.com

          git add .

          git diff --cached --quiet || git commit -m "News update"

          git push